name: workout-log
description: Workout Log
author:
  name: Andrew
  email: andrew@surfintegrated.io
future: true
show_drafts: true

# Markdown library
markdown: rdiscount
#   extensions: []

pygments: true

permalink: date
